"""clan war extended fields + member ranked_league

Revision ID: 0fc036606227
Revises: 00f3f82f75ca
Create Date: 2026-05-31 15:38:55.205915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fc036606227'
down_revision = '00f3f82f75ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clan_war', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clan_badge', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cwl_league', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('opponent_clan_badge', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('opponent_clan_location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('opponent_cwl_league', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('opponent_wars_won', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('opponent_war_frequency', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('opponent_win_streak', sa.Integer(), nullable=True))
        batch_op.drop_column('battle_modifier')
        batch_op.drop_column('attacks_per_member')

    with op.batch_alter_table('clan_war_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ranked_league', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clan_war_member', schema=None) as batch_op:
        batch_op.drop_column('ranked_league')

    with op.batch_alter_table('clan_war', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attacks_per_member', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('battle_modifier', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('opponent_win_streak')
        batch_op.drop_column('opponent_war_frequency')
        batch_op.drop_column('opponent_wars_won')
        batch_op.drop_column('opponent_cwl_league')
        batch_op.drop_column('opponent_clan_location')
        batch_op.drop_column('opponent_clan_badge')
        batch_op.drop_column('cwl_league')
        batch_op.drop_column('clan_badge')

    # ### end Alembic commands ###
