"""empty message

Revision ID: 42327ea8f198
Revises: b38a44b2bb38
Create Date: 2026-05-25 22:56:15.432419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42327ea8f198'
down_revision = 'b38a44b2bb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('league_icon',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)

    with op.batch_alter_table('ranked_week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_done', sa.Boolean(), nullable=True))
        batch_op.alter_column('league_icon',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranked_week', schema=None) as batch_op:
        batch_op.alter_column('league_icon',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('is_done')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('league_icon',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
