"""empty message

Revision ID: 6a3c35248594
Revises: 42327ea8f198
Create Date: 2026-05-26 11:58:50.333591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3c35248594'
down_revision = '42327ea8f198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raid_weekend',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('startTime', sa.DateTime(), nullable=False),
    sa.Column('endTime', sa.DateTime(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('capitalTotalLoot', sa.Integer(), nullable=True),
    sa.Column('raidsCompleted', sa.Integer(), nullable=True),
    sa.Column('totalAttacks', sa.Integer(), nullable=True),
    sa.Column('enemyDistrictsDestroyed', sa.Integer(), nullable=True),
    sa.Column('offensiveReward', sa.Integer(), nullable=True),
    sa.Column('defensiveReward', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'startTime', 'endTime')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raid_weekend')
    # ### end Alembic commands ###
