"""drop league_icon columns

Revision ID: 8b5d51eeb000
Revises: a1b2c3d4e5f6
Create Date: 2026-06-03 14:30:18.364445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b5d51eeb000'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('league_icon')

    with op.batch_alter_table('ranked_week', schema=None) as batch_op:
        batch_op.drop_column('league_icon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranked_week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_icon', mysql.VARCHAR(collation='utf8mb4_general_ci', length=150), nullable=True))

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_icon', mysql.VARCHAR(collation='utf8mb4_general_ci', length=150), nullable=True))

    # ### end Alembic commands ###
