"""equipment goals and user ores

Revision ID: a5e95f655592
Revises: a821165b0872
Create Date: 2026-06-14 22:19:48.019712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5e95f655592'
down_revision = 'a821165b0872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_goal',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('equipment_name', sa.String(length=100), nullable=False),
    sa.Column('target_level', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'equipment_name')
    )
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ore_shiny', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ore_glowy', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ore_starry', sa.Integer(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_column('ore_starry')
        batch_op.drop_column('ore_glowy')
        batch_op.drop_column('ore_shiny')

    op.drop_table('equipment_goal')
    # ### end Alembic commands ###
