"""empty message

Revision ID: b38a44b2bb38
Revises: 
Create Date: 2026-05-22 23:12:44.026873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38a44b2bb38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('current_th', sa.Integer(), nullable=True),
    sa.Column('in_clan', sa.Boolean(), nullable=True),
    sa.Column('league_tier', sa.String(length=50), nullable=True),
    sa.Column('league_icon', sa.String(length=100), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tag')
    )
    op.create_table('uptime_tracker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('function', sa.String(length=50), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battle_log',
    sa.Column('player_tag', sa.String(length=50), nullable=False),
    sa.Column('opponent_tag', sa.String(length=50), nullable=False),
    sa.Column('loot_gold', sa.Integer(), nullable=False),
    sa.Column('loot_elixir', sa.Integer(), nullable=False),
    sa.Column('loot_dark_elixir', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Boolean(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_tag'], ['player.tag'], ),
    sa.PrimaryKeyConstraint('player_tag', 'opponent_tag', 'loot_gold', 'loot_elixir', 'loot_dark_elixir')
    )
    op.create_table('ranked_week',
    sa.Column('league_group_tag', sa.String(length=50), nullable=False),
    sa.Column('league_season_id', sa.String(length=50), nullable=False),
    sa.Column('player_tag', sa.String(length=50), nullable=False),
    sa.Column('trophies', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('start_day', sa.Date(), nullable=True),
    sa.Column('end_day', sa.Date(), nullable=True),
    sa.Column('max_attacks', sa.Integer(), nullable=True),
    sa.Column('townhall', sa.Integer(), nullable=True),
    sa.Column('attack_wins', sa.Integer(), nullable=True),
    sa.Column('attack_losses', sa.Integer(), nullable=True),
    sa.Column('defense_wins', sa.Integer(), nullable=True),
    sa.Column('defense_losses', sa.Integer(), nullable=True),
    sa.Column('league_tier', sa.String(length=50), nullable=True),
    sa.Column('league_icon', sa.String(length=100), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_tag'], ['player.tag'], ),
    sa.PrimaryKeyConstraint('league_group_tag', 'league_season_id', 'player_tag')
    )
    op.create_table('ranked_battle_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opponent_tag', sa.String(length=50), nullable=False),
    sa.Column('league_group_tag', sa.String(length=50), nullable=True),
    sa.Column('league_season_id', sa.String(length=50), nullable=True),
    sa.Column('player_tag', sa.String(length=50), nullable=True),
    sa.Column('attack', sa.Boolean(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('trophies', sa.Integer(), nullable=True),
    sa.Column('opponent_name', sa.String(length=100), nullable=True),
    sa.Column('opponent_th', sa.String(length=100), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['league_group_tag', 'league_season_id', 'player_tag'], ['ranked_week.league_group_tag', 'ranked_week.league_season_id', 'ranked_week.player_tag'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ranked_battle_log')
    op.drop_table('ranked_week')
    op.drop_table('battle_log')
    op.drop_table('uptime_tracker')
    op.drop_table('player')
    # ### end Alembic commands ###
