"""add radar bucket sources

Revision ID: 01da83522036
Revises: b01b10f20a5b
Create Date: 2026-08-21 01:25:10.935805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01da83522036'
down_revision = 'b01b10f20a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radar_bucket_sources',
    sa.Column('ticker', sa.String(length=12, collation='utf8mb4_bin'), nullable=False),
    sa.Column('bucket_start', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('high_confidence_count', sa.Integer(), nullable=False),
    sa.Column('low_count', sa.Integer(), nullable=False),
    sa.Column('distinct_authors', sa.Integer(), nullable=False),
    sa.Column('distinct_text_ratio', sa.Float(), nullable=False),
    sa.Column('engagement_weighted_count', sa.Float(), nullable=False),
    sa.Column('sentiment_mean', sa.Float(), nullable=True),
    sa.Column('sentiment_stdev', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ok', 'missing', 'truncated', name='radar_source_status'), nullable=False),
    sa.Column('expected', sa.Float(), nullable=True),
    sa.Column('variance', sa.Float(), nullable=True),
    sa.Column('mention_z', sa.Float(), nullable=True),
    sa.Column('baseline_days', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'bucket_start', 'source'),
    mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('radar_bucket_sources', schema=None) as batch_op:
        batch_op.create_index('ix_radar_bucket_sources_start', ['bucket_start', 'source'], unique=False)

    with op.batch_alter_table('radar_buckets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('low_count', sa.Integer(), nullable=False))
        batch_op.drop_column('mention_z_stocktwits')
        batch_op.drop_column('baseline_days_stocktwits')
        batch_op.drop_column('count_reddit')
        batch_op.drop_column('mention_z_reddit')
        batch_op.drop_column('status_stocktwits')
        batch_op.drop_column('status_reddit')
        batch_op.drop_column('count_stocktwits')
        batch_op.drop_column('baseline_days_reddit')

    # ### end Alembic commands ###

    # Partitioned to match radar_buckets, which this table is joined to and
    # aged alongside. The primary key already contains bucket_start, which is
    # what makes this legal -- MySQL and MariaDB both require every unique key
    # to contain every partitioning column.
    #
    # There is deliberately no foreign key: InnoDB does not support them on
    # partitioned tables, so the relationship to radar_buckets is maintained by
    # convention and nothing enforces it.
    op.execute("""
        ALTER TABLE radar_bucket_sources
        PARTITION BY RANGE (TO_DAYS(bucket_start)) (
            PARTITION p_2026_08 VALUES LESS THAN (TO_DAYS('2026-09-01')),
            PARTITION p_2026_09 VALUES LESS THAN (TO_DAYS('2026-10-01')),
            PARTITION p_2026_10 VALUES LESS THAN (TO_DAYS('2026-11-01')),
            PARTITION p_2026_11 VALUES LESS THAN (TO_DAYS('2026-12-01')),
            PARTITION p_2026_12 VALUES LESS THAN (TO_DAYS('2027-01-01')),
            PARTITION p_max VALUES LESS THAN MAXVALUE
        )
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radar_buckets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baseline_days_reddit', mysql.SMALLINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('count_stocktwits', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status_reddit', mysql.ENUM('ok', 'missing', 'truncated'), nullable=False))
        batch_op.add_column(sa.Column('status_stocktwits', mysql.ENUM('ok', 'missing', 'truncated'), nullable=False))
        batch_op.add_column(sa.Column('mention_z_reddit', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('count_reddit', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('baseline_days_stocktwits', mysql.SMALLINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mention_z_stocktwits', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('low_count')

    with op.batch_alter_table('radar_bucket_sources', schema=None) as batch_op:
        batch_op.drop_index('ix_radar_bucket_sources_start')

    op.drop_table('radar_bucket_sources')
    # ### end Alembic commands ###
