"""add reconstructed_confidence to archived quiz questions

Revision ID: 1c5304b6e444
Revises: 81b8630f3c06
Create Date: 2026-06-20 22:01:50.419415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5304b6e444'
down_revision = '81b8630f3c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_quiz_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reconstructed_confidence', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_quiz_questions', schema=None) as batch_op:
        batch_op.drop_column('reconstructed_confidence')

    # ### end Alembic commands ###
