"""add radar source cursors

Revision ID: 38ff07e30e7a
Revises: 9985157b8538
Create Date: 2026-08-21 01:31:30.975589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38ff07e30e7a'
down_revision = '9985157b8538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radar_source_cursors',
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('cursor_utc', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('source'),
    mysql_charset='utf8mb4'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radar_source_cursors')
    # ### end Alembic commands ###
