"""add source config version to bucket sources

Revision ID: 435a6e5a4cf0
Revises: f6d2b6268488
Create Date: 2026-08-21 13:22:01.967492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435a6e5a4cf0'
down_revision = 'f6d2b6268488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radar_bucket_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_config_version', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radar_bucket_sources', schema=None) as batch_op:
        batch_op.drop_column('source_config_version')

    # ### end Alembic commands ###
