"""collapse question_text and reconstructed_text into a single field with AI flag

Revision ID: 550f78a86ec3
Revises: 1c5304b6e444
Create Date: 2026-06-20 22:25:35.905935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '550f78a86ec3'
down_revision = '1c5304b6e444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_quiz_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ai_reconstructed', sa.Boolean(), nullable=False))
        batch_op.drop_column('reconstructed_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_quiz_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reconstructed_text', mysql.TEXT(), nullable=True))
        batch_op.drop_column('is_ai_reconstructed')

    # ### end Alembic commands ###
