"""add delivery_shifts table

Revision ID: 5674f500edd9
Revises: cb85ccb17035
Create Date: 2026-06-17 19:22:33.375140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5674f500edd9'
down_revision = 'cb85ccb17035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_shifts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_start', sa.Time(), nullable=True),
    sa.Column('shift_end', sa.Time(), nullable=True),
    sa.Column('hours_worked', sa.Float(), nullable=False),
    sa.Column('tips_cash', sa.Float(), nullable=True),
    sa.Column('tips_online', sa.Float(), nullable=True),
    sa.Column('deliveries', sa.Integer(), nullable=True),
    sa.Column('bike_size', sa.String(length=10), nullable=True),
    sa.Column('weather', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_shifts')
    # ### end Alembic commands ###
