"""add set completed flag and session resting_set_id

Revision ID: 69ab88376315
Revises: a17b30f0207c
Create Date: 2026-07-03 02:18:14.578261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ab88376315'
down_revision = 'a17b30f0207c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_session_sets', schema=None) as batch_op:
        # server_default needed so this doesn't fail under MySQL strict mode on
        # a table that already has rows; existing (already-performed) sets are
        # backfilled as completed=True, matching their real-world state.
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=False, server_default=sa.true()))

    with op.batch_alter_table('gym_workout_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resting_set_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'gym_session_sets', ['resting_set_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_workout_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('resting_set_id')

    with op.batch_alter_table('gym_session_sets', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
