"""add radar tables

Revision ID: 7883c6e08708
Revises: a1c95e7b4d02
Create Date: 2026-08-20 20:27:27.682477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7883c6e08708'
down_revision = 'a1c95e7b4d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radar_buckets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=12, collation='utf8mb4_bin'), nullable=False),
    sa.Column('bucket_start', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('high_confidence_count', sa.Integer(), nullable=False),
    sa.Column('distinct_authors', sa.Integer(), nullable=False),
    sa.Column('distinct_text_ratio', sa.Float(), nullable=False),
    sa.Column('engagement_weighted_count', sa.Float(), nullable=False),
    sa.Column('sentiment_mean', sa.Float(), nullable=True),
    sa.Column('sentiment_stdev', sa.Float(), nullable=True),
    sa.Column('count_reddit', sa.Integer(), nullable=False),
    sa.Column('count_stocktwits', sa.Integer(), nullable=False),
    sa.Column('status_reddit', sa.Enum('ok', 'missing', 'truncated', name='radar_source_status'), nullable=False),
    sa.Column('status_stocktwits', sa.Enum('ok', 'missing', 'truncated', name='radar_source_status'), nullable=False),
    sa.Column('sources_ok', sa.SmallInteger(), nullable=False),
    sa.Column('source_config_version', sa.String(length=16), nullable=False),
    sa.Column('mention_z_reddit', sa.Float(), nullable=True),
    sa.Column('mention_z_stocktwits', sa.Float(), nullable=True),
    sa.Column('baseline_days_reddit', sa.SmallInteger(), nullable=True),
    sa.Column('baseline_days_stocktwits', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'bucket_start'),
    sa.UniqueConstraint('ticker', 'bucket_start', name='uq_radar_bucket'),
    mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('radar_buckets', schema=None) as batch_op:
        batch_op.create_index('ix_radar_buckets_start_ticker', ['bucket_start', 'ticker'], unique=False)

    op.create_table('radar_posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('created_utc', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('body', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('simhash', sa.BigInteger(), nullable=False),
    sa.Column('first_seen', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('last_seen', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_radar_post_source_ext'),
    mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('radar_posts', schema=None) as batch_op:
        batch_op.create_index('ix_radar_posts_created_utc', ['created_utc'], unique=False)

    op.create_table('radar_ticker_universe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=12, collation='utf8mb4_bin'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('first_seen', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('delisted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('radar_ticker_universe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_radar_ticker_universe_symbol'), ['symbol'], unique=True)

    op.create_table('radar_mentions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.String(length=12, collation='utf8mb4_bin'), nullable=False),
    sa.Column('confidence', sa.Enum('high', 'medium', name='radar_confidence'), nullable=False),
    sa.Column('lexicon_sentiment', sa.Float(), nullable=True),
    sa.Column('llm_sentiment', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['radar_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('radar_mentions', schema=None) as batch_op:
        batch_op.create_index('ix_radar_mentions_post', ['post_id'], unique=False)
        batch_op.create_index('ix_radar_mentions_ticker_post', ['ticker', 'post_id'], unique=False)

    # radar_buckets is retained forever. Monthly RANGE partitions keep the
    # 30-day baseline scan inside one or two partitions. The unique key
    # already contains bucket_start, which is what makes this legal.
    op.execute("""
        ALTER TABLE radar_buckets
        PARTITION BY RANGE (TO_DAYS(bucket_start)) (
            PARTITION p_2026_08 VALUES LESS THAN (TO_DAYS('2026-09-01')),
            PARTITION p_2026_09 VALUES LESS THAN (TO_DAYS('2026-10-01')),
            PARTITION p_2026_10 VALUES LESS THAN (TO_DAYS('2026-11-01')),
            PARTITION p_2026_11 VALUES LESS THAN (TO_DAYS('2026-12-01')),
            PARTITION p_2026_12 VALUES LESS THAN (TO_DAYS('2027-01-01')),
            PARTITION p_max VALUES LESS THAN MAXVALUE
        )
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radar_mentions', schema=None) as batch_op:
        batch_op.drop_index('ix_radar_mentions_ticker_post')
        batch_op.drop_index('ix_radar_mentions_post')

    op.drop_table('radar_mentions')
    with op.batch_alter_table('radar_ticker_universe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radar_ticker_universe_symbol'))

    op.drop_table('radar_ticker_universe')
    with op.batch_alter_table('radar_posts', schema=None) as batch_op:
        batch_op.drop_index('ix_radar_posts_created_utc')

    op.drop_table('radar_posts')
    with op.batch_alter_table('radar_buckets', schema=None) as batch_op:
        batch_op.drop_index('ix_radar_buckets_start_ticker')

    op.drop_table('radar_buckets')
    # ### end Alembic commands ###
