"""restructure quiz archive into rounds with trivia, picture, music

Revision ID: 7bbac5179456
Revises: 5674f500edd9
Create Date: 2026-06-20 21:27:32.549487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bbac5179456'
down_revision = '5674f500edd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_quizzes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('venue', sa.String(length=150), nullable=True),
    sa.Column('quizmaster', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archived_quiz_rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('round_type', sa.String(length=20), nullable=False),
    sa.Column('topic', sa.String(length=150), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['archived_quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archived_quiz_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['archived_quiz_rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archived_quiz_songs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['archived_quiz_rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archived_quiz_songs')
    op.drop_table('archived_quiz_questions')
    op.drop_table('archived_quiz_rounds')
    op.drop_table('archived_quizzes')
    # ### end Alembic commands ###
