"""add reconstructed_text to archived quiz questions

Revision ID: 81b8630f3c06
Revises: 7bbac5179456
Create Date: 2026-06-20 21:34:51.719687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b8630f3c06'
down_revision = '7bbac5179456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_quiz_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reconstructed_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_quiz_questions', schema=None) as batch_op:
        batch_op.drop_column('reconstructed_text')

    # ### end Alembic commands ###
