"""add radar poll state

Revision ID: 9985157b8538
Revises: 01da83522036
Create Date: 2026-08-21 01:29:39.266765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9985157b8538'
down_revision = '01da83522036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radar_poll_state',
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('symbol', sa.String(length=12, collation='utf8mb4_bin'), nullable=False),
    sa.Column('last_polled_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('next_due_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('observed_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('source', 'symbol'),
    mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('radar_poll_state', schema=None) as batch_op:
        batch_op.create_index('ix_radar_poll_state_due', ['source', 'next_due_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radar_poll_state', schema=None) as batch_op:
        batch_op.drop_index('ix_radar_poll_state_due')

    op.drop_table('radar_poll_state')
    # ### end Alembic commands ###
