"""add rest_seconds to session exercises

Revision ID: a17b30f0207c
Revises: ebf7bd2c60a7
Create Date: 2026-07-03 01:56:31.614936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17b30f0207c'
down_revision = 'ebf7bd2c60a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_session_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rest_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_session_exercises', schema=None) as batch_op:
        batch_op.drop_column('rest_seconds')

    # ### end Alembic commands ###
