"""add cached daily sigma

Revision ID: c2138190d95a
Revises: e91f50cd68ac
Create Date: 2026-08-22 01:34:10.413079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2138190d95a'
down_revision = 'e91f50cd68ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radar_ticker_universe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_sigma', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sigma_refreshed_at', mysql.DATETIME(fsp=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radar_ticker_universe', schema=None) as batch_op:
        batch_op.drop_column('sigma_refreshed_at')
        batch_op.drop_column('daily_sigma')

    # ### end Alembic commands ###
