"""add rest_seconds to template exercises

Revision ID: caa1c8f9ca8b
Revises: 69ab88376315
Create Date: 2026-07-03 03:04:47.835439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa1c8f9ca8b'
down_revision = '69ab88376315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_template_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rest_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_template_exercises', schema=None) as batch_op:
        batch_op.drop_column('rest_seconds')

    # ### end Alembic commands ###
