"""create quiz_rounds and quiz_teams

Revision ID: cb85ccb17035
Revises: 
Create Date: 2026-06-17 17:35:27.753518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb85ccb17035'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=True),
    sa.Column('bilderrunde', sa.String(length=100), nullable=True),
    sa.Column('quizmaster', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('round1_points', sa.Float(), nullable=True),
    sa.Column('round2_points', sa.Float(), nullable=True),
    sa.Column('round3_points', sa.Float(), nullable=True),
    sa.Column('round4_points', sa.Float(), nullable=True),
    sa.Column('round1_size', sa.Integer(), nullable=True),
    sa.Column('round2_size', sa.Integer(), nullable=True),
    sa.Column('round3_size', sa.Integer(), nullable=True),
    sa.Column('round4_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['quiz_rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_teams')
    op.drop_table('quiz_rounds')
    # ### end Alembic commands ###
