"""add replaces_id to session exercises

Revision ID: d4f8b2a91c6e
Revises: caa1c8f9ca8b
Create Date: 2026-07-08 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f8b2a91c6e'
down_revision = 'caa1c8f9ca8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_session_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replaces_id', sa.Integer(), nullable=True))
        # ondelete='SET NULL' -- deleting a session-exercise that a substitute
        # still points at (via replaces_id) must detach the substitute rather
        # than fail with a FK violation (MySQL/InnoDB defaults to RESTRICT).
        batch_op.create_foreign_key(
            'fk_gym_session_exercises_replaces_id', 'gym_session_exercises', ['replaces_id'], ['id'],
            ondelete='SET NULL',
        )
        # At most one substitute per original: the ORM's `replaced_by` backref
        # assumes uselist=False, but that's only an app-level assumption
        # unless the schema enforces it too. MySQL unique indexes allow
        # multiple NULLs, so ordinary (non-substitute) rows are unaffected.
        batch_op.create_unique_constraint('uq_gym_session_exercises_replaces_id', ['replaces_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_session_exercises', schema=None) as batch_op:
        batch_op.drop_constraint('uq_gym_session_exercises_replaces_id', type_='unique')
        batch_op.drop_constraint('fk_gym_session_exercises_replaces_id', type_='foreignkey')
        batch_op.drop_column('replaces_id')

    # ### end Alembic commands ###
