"""add radar quotes and profile fields

Revision ID: e91f50cd68ac
Revises: 435a6e5a4cf0
Create Date: 2026-08-22 01:01:48.635362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e91f50cd68ac'
down_revision = '435a6e5a4cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radar_quotes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=12, collation='utf8mb4_bin'), nullable=False),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('quote_ts', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('prev_close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'fetched_at', name='uq_radar_quote'),
    mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('radar_quotes', schema=None) as batch_op:
        batch_op.create_index('ix_radar_quotes_ticker_fetched', ['ticker', 'fetched_at'], unique=False)

    with op.batch_alter_table('radar_ticker_universe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True))
        batch_op.add_column(sa.Column('ipo_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('next_earnings_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('profile_refreshed_at', mysql.DATETIME(fsp=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radar_ticker_universe', schema=None) as batch_op:
        batch_op.drop_column('profile_refreshed_at')
        batch_op.drop_column('next_earnings_date')
        batch_op.drop_column('ipo_date')
        batch_op.drop_column('market_cap')

    with op.batch_alter_table('radar_quotes', schema=None) as batch_op:
        batch_op.drop_index('ix_radar_quotes_ticker_fetched')

    op.drop_table('radar_quotes')
    # ### end Alembic commands ###
