"""add gym tracker tables

Revision ID: ebf7bd2c60a7
Revises: 1cdcdfc9d2d6
Create Date: 2026-07-03 01:25:51.510439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf7bd2c60a7'
down_revision = '1cdcdfc9d2d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('muscle_group', sa.String(length=100), nullable=True),
    sa.Column('default_rest_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gym_push_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('p256dh_key', sa.String(length=255), nullable=False),
    sa.Column('auth_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_table('gym_workout_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gym_template_exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['gym_exercises.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['gym_workout_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gym_workout_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('rest_ends_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['gym_workout_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gym_pending_pushes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('fire_at', sa.DateTime(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['gym_workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gym_session_exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['gym_exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['gym_workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gym_session_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['gym_session_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gym_session_sets')
    op.drop_table('gym_session_exercises')
    op.drop_table('gym_pending_pushes')
    op.drop_table('gym_workout_sessions')
    op.drop_table('gym_template_exercises')
    op.drop_table('gym_workout_templates')
    op.drop_table('gym_push_subscriptions')
    op.drop_table('gym_exercises')
    # ### end Alembic commands ###
