"""add radar daily closes

Revision ID: ef00e6c43e25
Revises: c2138190d95a
Create Date: 2026-08-23 10:56:54.551772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef00e6c43e25'
down_revision = 'c2138190d95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radar_daily_closes',
    sa.Column('ticker', sa.String(length=12, collation='utf8mb4_bin'), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'close_date'),
    mysql_charset='utf8mb4'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radar_daily_closes')
    # ### end Alembic commands ###
