"""add status error_message summary to uptime_tracker

Revision ID: 00f3f82f75ca
Revises: d417b03684b3
Create Date: 2026-05-31 14:33:27.086938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f3f82f75ca'
down_revision = 'd417b03684b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uptime_tracker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uptime_tracker', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('error_message')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
