"""add clan_name to clan_war

Revision ID: 138728b2a169
Revises: 0fc036606227
Create Date: 2026-05-31 15:53:16.212000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138728b2a169'
down_revision = '0fc036606227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clan_war_attack',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clan_war_id', sa.Integer(), nullable=True),
    sa.Column('attacker_tag', sa.String(length=30), nullable=True),
    sa.Column('defender_tag', sa.String(length=30), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('destruction_pct', sa.Float(), nullable=True),
    sa.Column('attack_order', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clan_war_id'], ['clan_war.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clan_war', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clan_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clan_war', schema=None) as batch_op:
        batch_op.drop_column('clan_name')

    op.drop_table('clan_war_attack')
    # ### end Alembic commands ###
