"""empty message

Revision ID: 29c24614ac82
Revises: 42dd68eb5b6b
Create Date: 2026-05-26 14:18:12.533986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c24614ac82'
down_revision = '42dd68eb5b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raid_weekend_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentageTotal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raid_weekend_log', schema=None) as batch_op:
        batch_op.drop_column('percentageTotal')

    # ### end Alembic commands ###
