"""empty message

Revision ID: 42dd68eb5b6b
Revises: 6a3c35248594
Create Date: 2026-05-26 13:59:11.607539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42dd68eb5b6b'
down_revision = '6a3c35248594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raid_weekend_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raid_weekend_id', sa.Integer(), nullable=True),
    sa.Column('defenderName', sa.String(length=30), nullable=True),
    sa.Column('defenderTag', sa.String(length=30), nullable=True),
    sa.Column('districtName', sa.String(length=30), nullable=True),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('isCleanUp', sa.Boolean(), nullable=True),
    sa.Column('playerTag', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['playerTag'], ['player.tag'], ),
    sa.ForeignKeyConstraint(['raid_weekend_id'], ['raid_weekend.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raid_weekend_log')
    # ### end Alembic commands ###
