"""fix pubquiz fk and add relationships

Revision ID: 7163616714f9
Revises: 29c24614ac82
Create Date: 2026-05-26 23:08:15.553170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7163616714f9'
down_revision = '29c24614ac82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pubquiz_rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=True),
    sa.Column('bilderrunde', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pubquiz_teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('round1_points', sa.Integer(), nullable=True),
    sa.Column('round2_points', sa.Integer(), nullable=True),
    sa.Column('round3_points', sa.Integer(), nullable=True),
    sa.Column('round1_size', sa.Integer(), nullable=True),
    sa.Column('round2_size', sa.Integer(), nullable=True),
    sa.Column('round3_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['pubquiz_rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pubquiz_teams')
    op.drop_table('pubquiz_rounds')
    # ### end Alembic commands ###
