"""castle_empty is_rushed is_troll perm_clan_war_edits

Revision ID: 7d396e785c8d
Revises: c2d3e4f5a6b7
Create Date: 2026-06-01 00:39:14.254162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d396e785c8d'
down_revision = 'c2d3e4f5a6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perm_clan_war_edits', sa.Boolean(), nullable=False))

    with op.batch_alter_table('clan_war', schema=None) as batch_op:
        batch_op.add_column(sa.Column('castle_empty', sa.Boolean(), nullable=False))

    with op.batch_alter_table('clan_war_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_rushed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_troll', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clan_war_member', schema=None) as batch_op:
        batch_op.drop_column('is_troll')
        batch_op.drop_column('is_rushed')

    with op.batch_alter_table('clan_war', schema=None) as batch_op:
        batch_op.drop_column('castle_empty')

    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_column('perm_clan_war_edits')

    # ### end Alembic commands ###
