"""Init

Revision ID: 80ee59e9ffde
Revises: 59a371e0c374
Create Date: 2026-05-22 15:13:07.199596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80ee59e9ffde'
down_revision = '59a371e0c374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uptime_tracker', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=mysql.TIME(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uptime_tracker', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.String(length=50),
               type_=mysql.TIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
