"""add clan location wins frequency streak

Revision ID: a21ca9607055
Revises: 138728b2a169
Create Date: 2026-05-31 15:57:42.589732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21ca9607055'
down_revision = '138728b2a169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clan_war', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clan_location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('clan_wars_won', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('clan_war_frequency', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('clan_win_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clan_war', schema=None) as batch_op:
        batch_op.drop_column('clan_win_streak')
        batch_op.drop_column('clan_war_frequency')
        batch_op.drop_column('clan_wars_won')
        batch_op.drop_column('clan_location')

    # ### end Alembic commands ###
