"""add clan war tables

Revision ID: d417b03684b3
Revises: 751c42eac652
Create Date: 2026-05-31 01:27:52.232202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd417b03684b3'
down_revision = '751c42eac652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clan_war',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('attacks_per_member', sa.Integer(), nullable=True),
    sa.Column('battle_modifier', sa.String(length=50), nullable=True),
    sa.Column('preparation_start_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('opponent_tag', sa.String(length=30), nullable=True),
    sa.Column('opponent_name', sa.String(length=100), nullable=True),
    sa.Column('opponent_clan_level', sa.Integer(), nullable=True),
    sa.Column('clan_stars', sa.Integer(), nullable=True),
    sa.Column('clan_attacks', sa.Integer(), nullable=True),
    sa.Column('clan_destruction_pct', sa.Float(), nullable=True),
    sa.Column('opponent_stars', sa.Integer(), nullable=True),
    sa.Column('opponent_attacks', sa.Integer(), nullable=True),
    sa.Column('opponent_destruction_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_time')
    )
    op.create_table('clan_war_attack',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clan_war_id', sa.Integer(), nullable=True),
    sa.Column('attacker_tag', sa.String(length=30), nullable=True),
    sa.Column('defender_tag', sa.String(length=30), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('destruction_pct', sa.Float(), nullable=True),
    sa.Column('attack_order', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clan_war_id'], ['clan_war.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clan_war_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clan_war_id', sa.Integer(), nullable=True),
    sa.Column('is_opponent', sa.Boolean(), nullable=False),
    sa.Column('player_tag', sa.String(length=30), nullable=True),
    sa.Column('player_name', sa.String(length=100), nullable=True),
    sa.Column('town_hall_level', sa.Integer(), nullable=True),
    sa.Column('map_position', sa.Integer(), nullable=True),
    sa.Column('opponent_attacks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clan_war_id'], ['clan_war.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clan_war_member')
    op.drop_table('clan_war_attack')
    op.drop_table('clan_war')
    # ### end Alembic commands ###
