"""drop isCleanUp from raid_weekend_log

Revision ID: d73dcf2cf30c
Revises: d3e9f2a71c04
Create Date: 2026-05-30 01:09:20.025797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd73dcf2cf30c'
down_revision = 'd3e9f2a71c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raid_weekend_log', schema=None) as batch_op:
        batch_op.drop_column('isCleanUp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raid_weekend_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isCleanUp', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
