"""empty message

Revision ID: f4d12da7510b
Revises: a9f88ac3f70a
Create Date: 2026-05-28 15:08:05.776879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d12da7510b'
down_revision = 'a9f88ac3f70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raid_weekend_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('districLevel', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('totalLootAllAttacks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raid_weekend_log', schema=None) as batch_op:
        batch_op.drop_column('totalLootAllAttacks')
        batch_op.drop_column('districLevel')

    # ### end Alembic commands ###
